### ISSUE TITLE
Update the recommended VSCode Nim extension in the README

### ISSUE THREAD

**Issue by samdze** [samdze/playdate-nim#70]
The recommended extension should become [this one](https://marketplace.visualstudio.com/items?itemName=NimLang.nimlang), which is the new official Nim language support extension for Visual Studio Code.

**Comment by ninovanhooff** [comment]
Wait until nim 2 is merged though, since the official plugin downloads and compiles some component, I think it was nim-suggest. This is not supported and fails on nim 1.6, requiring users to manually get that.
Until they do the plugin retries this process on every restart of vscode. Very annoying. 

Even then, I wouldn't assume that the official one is in better shape than nimsaem. Test-drive it for some time in a real project first. I did revert to nimsaem, can't recall the exact reason atm. Anyways, let's hope it's the better choice for nim 2.
