### ISSUE TITLE
Discrepancy between main README and currently latest version (v0.13)

### ISSUE THREAD

**Issue by ninovanhooff** [samdze/playdate-nim#75]
**Problem**

The example project currently will not compile when used with the bindings downloaded from Nimble. This is because multiple breaking changes have been introduced (audio player finish callback and button~s~State rename.

Reported here by user `Dork`:
https://discord.com/channels/675983554655551509/1229190504583921694/1246518505176694898

**Fix**
Create a new release so Nimble is up to date with main

**Prevent regression**
To prevent this from happening again, a `develop` branch should be introduced. `develop` is only merged to `main` when a new release is made, so that `main` always represents what users will get when using `requires "playdate"`. This then also applies for the README.md and the example project.

**Comment by samdze** [comment]
This is something we can improve on.
The intended way to view stable versions of the codebase right now is to select the version tag from the list of release tags, so that each user can inspect the code/docs for the version of the bindings they are using.

This in theory gives the most flexibility without the need for an additional branch, but it is less convenient for newcomers.
So yeah, probably a `dev` branch is the way to go to streamline adoption during development of breaking changes.

In the meantime I'll work on releasing a new functioning package release

**Comment by ninovanhooff** [comment]
@samdze let's go with dev then? I only prefer develop out of habit, would be fine to go with dev

**Comment by samdze** [comment]
Yes, I'm ok with that!
